# Generated by Django 3.1.5 on 2021-01-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('aprovado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gabarito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('aluno_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gradesmanager.aluno')),
                ('gabarito_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gradesmanager.gabarito')),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('prova_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradesmanager.prova')),
            ],
        ),
        migrations.AddField(
            model_name='prova',
            name='respostas_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gradesmanager.respostas'),
        ),
    ]
