# Generated by Django 3.1.5 on 2021-01-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
