# Generated by Django 3.1.5 on 2021-01-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradesmanager', '0003_auto_20210129_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
